### ISSUE TITLE
Write access

### ISSUE THREAD

**Issue by Aviortheking** [textbook/git-checkout-submodule-action#12]
We don't have write access to the submodules

ex:
https://github.com/tcgdex/compiler/runs/2391328256?check_suite_focus=true
error TS5033: Could not write file '/home/runner/work/compiler/compiler/db/data/Base.js': EACCES: permission denied, open '/home/runner/work/compiler/compiler/db/data/Base.js'.

**Comment by Eversor** [comment]
I can confirm, i ended up losing an hour to this problem...
