### ISSUE TITLE
syntax error in entrypoint.sh

### ISSUE THREAD

**Issue by thomasrudin** [textbook/git-checkout-submodule-action#4]
The action fails since https://github.com/textbook/git-checkout-submodule-action/commit/7ab4546b1ba1bc52c9f2f44dfb297890224815e5#diff-b958f585a04af5ee2087610ea7180f34 with the error:

```
/entrypoint.sh: 5: /entrypoint.sh: Syntax error: "(" unexpected
```

Thanks for the work by the way :+1:

**Comment by sandsbit** [comment]
Have same problem. ~~Maybe I will fix it by myself and start pull request~~

**Comment by iberisoft** [comment]
Have the same
