### ISSUE TITLE
cloning submodule in the wrong directory

### ISSUE THREAD

**Issue by zosrothko** [textbook/git-checkout-submodule-action#6]
Hi

I am using the git-checkout-submodule-action to checkout my submodule, but the working directory where is put the submodule is wrong. Submodule `codegen` should be cloned into`/home/runner/work/javacc/javacc` instead of  `/github/workspace`. See the action [8.0.0.yaml](https://github.com/javacc/javacc/blob/8.0.0/.github/workflows/8.0.0.yaml)
```
Checkout submodules
1s
Submodule path 'codegen': checked out 'f7bed9223aa4f12b444ffbeb2c8b2066d290174a'
Run textbook/git-checkout-submodule-action@master
/usr/bin/docker run --name e87b52c8af41dcdd2248488a6b2c91fdd6c9db_3141b8 --label e87b52 --workdir /github/workspace --rm -e INPUT_REMOTE -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/javacc/javacc":"/github/workspace" e87b52:c8af41dcdd2248488a6b2c91fdd6c9db  "true"
Submodule 'codegen' (https://github.com/javacc/codegenerator.git) registered for path 'codegen'
Cloning into '/github/workspace/codegen'...
Submodule path 'codegen': checked out 'f7bed9223aa4f12b444ffbeb2c8b2066d290174a'
```
below the .gitmodules content
```
[submodule "codegen"]
	path = codegen
	url = https://github.com/javacc/codegenerator.git
	branch = master
```

**Comment by textbook** [comment]
It's not clear to me where the information about the alternative directory would come from - you can see in `.gitmodules` that the `path`, the [_"the path, relative to the top-level directory of the Git working tree, where the submodule is expected to be checked out"_](https://www.git-scm.com/docs/gitmodules#Documentation/gitmodules.txt-submoduleltnamegtpath), is `codegen` so this behaviour is what I'd expect. I don't think this is something the action can handle.
